development:
  adapter: sqlite3
  database: lemonade_db
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: lemonade_db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: lemonade_db
  pool: 5
  timeout: 5000